
CREATE TABLE youtube_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id VARCHAR(255) NOT NULL UNIQUE,

    access_token_encrypted TEXT NOT NULL,
    refresh_token_encrypted TEXT,

    expires_at TIMESTAMPTZ,
    scopes TEXT,
    token_type VARCHAR(50),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_youtube_tokens_user_id
    ON youtube_tokens (user_id);
