spring:
    application:
        name: youtube-agent
    config:
        import: optional:file:.env/.env.${spring.profiles.active:local}[.properties]
    security:
        oauth2:
            client:
                registration:
                  google:
                    client-id: ${GOOGLE_CLIENT_ID}
                    client-secret: ${GOOGLE_CLIENT_SECRET}
                    scope:
                      - openid
                      - profile
                      - email

app:
    frontend-url: ${APP_FRONTEND_URL:http://localhost:5173}

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm.SSS} %-5level %logger{0} [%X{requestId:-}] - %msg%n"
    level:
        root: INFO
        # com:
            # youtubeagent: DEBUG

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics
    endpoint:
        health:
            show-details: when-authorized

youtube:
    google-o-auth:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        redirect-uri: ${GOOGLE_REDIRECT_URI}
    
    token-storage:
        file-path: .data/youtube-token.enc
        encryption-key: ${YOUTUBE_TOKEN_ENCRYPTION_KEY}

ai:
    providers:
        ollama:
            base-url: http://localhost:11434
            model: qwen3:4b

        groq:
            api-key: ${AI_GROQ_API_KEY}
            base-url: https://api.groq.com/openai/v1

        gemini:
            api-key: ${AI_GEMINI_API_KEY}
            base-url: https://generativelanguage.googleapis.com

        huggingface:
            api-key: ${AI_HUGGINGFACE_API_KEY}
            base-url: https://router.huggingface.co

        openai:
            api-key: ${AI_OPENAI_API_KEY}
            base-url: https://api.openai.com

        openrouter:
            api-key: ${AI_OPENROUTER_API_KEY}
            base-url: https://openrouter.ai/api
        
        bytez:
            api-key: ${AI_BYTEZ_API_KEY}
            base-url: https://api.bytez.com
        
        nvidia:
            api-key: ${AI_NVIDIA_API_KEY}
            base-url: https://integrate.api.nvidia.com

    models:

        - id: nvidia/nemotron-3-ultra-550b-a55b:free
          provider: openrouter
          priority: 1
          free: true
          capabilities:
          - TOOL_CALLING
          - JSON
          - CHAT

        - id: apodex/apodex-1.1-mini:free
          provider: openrouter
          priority: 2
          free: true
          capabilities:
          - TOOL_CALLING
          - JSON
          - CHAT

        - id: nvidia/nemotron-3.5-lightning:free
          provider: openrouter
          priority: 3
          free: true
          capabilities:
            - TOOL_CALLING
            - JSON
            - CHAT