spring:
    application:
        name: youtube-agent
    config:
        import: optional:file:.env/.env.${spring.profiles.active:local}[.properties]


management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics
    endpoint:
        health:
            show-details: when-authorized

ai:
    providers:
        ollama:
            base-url: http://localhost:11434
            model: qwen3:4b

        groq:
            api-key: ${AI_GROQ_API_KEY}
            base-url: https://api.groq.com/openai/v1

        gemini:
            api-key: ${AI_GEMINI_API_KEY}
            base-url: https://generativelanguage.googleapis.com

        huggingface:
            api-key: ${AI_HUGGINGFACE_API_KEY}
            base-url: https://router.huggingface.co

        openai:
            api-key: ${AI_OPENAI_API_KEY}
            base-url: https://api.openai.com

        openrouter:
            api-key: ${AI_OPENROUTER_API_KEY}
            base-url: https://openrouter.ai/api
        
        bytez:
            api-key: ${AI_BYTEZ_API_KEY}
            base-url: https://api.bytez.com
        
        nvidia:
            api-key: ${AI_NVIDIA_API_KEY}
            base-url: https://integrate.api.nvidia.com

    models:

        # OpenRouter
        - id: meta-llama/llama-3.3-70b-instruct
          provider: openrouter
          free: true
          priority: 1
          capabilities:
              - CHAT
              - JSON
              - TOOL_CALLING

        - id: google/gemma-3-27b-it
          provider: openrouter
          free: true
          priority: 2
          capabilities:
              - CHAT
              - JSON

        - id: deepseek-ai/deepseek-v4.1-flash
          provider: nvidia
          free: true
          priority: 3
          capabilities:
          - CHAT
          - JSON
          - TOOL_CALLING
